// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getDatabaseUrl(): string {
  // Use DATABASE_URL if it exists and starts with mysql://
  if (process.env["DATABASE_URL"] && process.env["DATABASE_URL"].startsWith("mysql://")) {
    return process.env["DATABASE_URL"];
  }

  // Otherwise, construct from individual environment variables
  const username = process.env.DB_USERNAME || "root";
  const password = process.env.DB_PASSWORD || "";
  const host = process.env.DB_HOST || "localhost";
  const port = process.env.DB_PORT || "3306";
  const database = process.env.DB_DATABASE || "lyzer-nextjs";

  // Handle empty password (no password after colon)
  const passwordPart = password ? `:${password}` : "";
  return `mysql://${username}${passwordPart}@${host}:${port}/${database}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
