-- CreateTable
CREATE TABLE `engineering_wikis` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `customer_name` VARCHAR(255) NULL,
    `category` ENUM('issue', 'update', 'note') NOT NULL DEFAULT 'note',
    `brand` VARCHAR(255) NULL,
    `device_type` VARCHAR(255) NULL,
    `model` VARCHAR(255) NULL,
    `serial_number` VARCHAR(255) NULL,
    `firmware_version` VARCHAR(255) NULL,
    `hardware_version` VARCHAR(255) NULL,
    `symptom` TEXT NULL,
    `symptom_file` VARCHAR(500) NULL,
    `symptom_image` VARCHAR(500) NULL,
    `root_cause` TEXT NULL,
    `root_cause_file` VARCHAR(500) NULL,
    `root_cause_image` VARCHAR(500) NULL,
    `solution` TEXT NULL,
    `solution_file` VARCHAR(500) NULL,
    `solution_image` VARCHAR(500) NULL,
    `action_taken` TEXT NULL,
    `action_taken_file` VARCHAR(500) NULL,
    `action_taken_image` VARCHAR(500) NULL,
    `status` ENUM('open', 'monitoring', 'solved', 'closed') NOT NULL DEFAULT 'open',
    `priority` ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
    `reference_doc` VARCHAR(255) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NULL,

    INDEX `idx_category`(`category`),
    INDEX `idx_status`(`status`),
    INDEX `idx_priority`(`priority`),
    INDEX `idx_brand`(`brand`),
    INDEX `idx_device_type`(`device_type`),
    INDEX `idx_created_at`(`created_at`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
