// Modbus Configuration Constants

export const SYSTEM_TYPE_OPTIONS = {
  1: '1P2W',
  2: '3P3W Unbal',
  3: '3P4W Unbal',
  4: 'U31 I1 Bal',
  5: 'U23 I1 Bal',
  6: 'U12 I1 Bal',
  7: '3P3W Bal',
  8: '3P4W Bal',
}

export const PARAM_SELECT_OPTIONS = {
  0: 'Volts 1',
  1: 'Volts 2',
  2: 'Volts 3',
  3: 'Current 1',
  4: 'Current 2',
  5: 'Current 3',
  6: 'Watt 1',
  7: 'Watt 2',
  8: 'Watt 3',
  9: 'VA 1',
  10: 'VA 2',
  11: 'VA 3',
  12: 'VAr 1',
  13: 'VAr 2',
  14: 'VAr 3',
  15: 'PF 1',
  16: 'PF 2',
  17: 'PF 3',
  18: 'PA 1',
  19: 'PA 2',
  20: 'PA 3',
  21: 'Volts Average',
  23: 'Current Average',
  26: 'Watts sum',
  28: 'VA sum',
  30: 'VAr sum',
  31: 'PF Average',
  33: 'PA Average',
  35: 'Frequency',
  84: 'Re-Active PF L1',
  85: 'Re-Active PF L2',
  86: 'Re-Active PF L3',
  87: 'Avg Re-Active PF',
  89: 'LF SgnQ(1-(P/S)) L1',
  90: 'LF SgnQ(1-(P/S)) L2',
  91: 'LF SgnQ(1-(P/S)) L3',
  92: 'Avg LF SgnQ(1-(P/S))',
  100: 'V1-2',
  101: 'V2-3',
  102: 'V3-1',
  127: 'Distortion VAr L1',
  128: 'Distortion VAr L2',
  129: 'Distortion VAr L3',
  131: 'SUM Distortion VAr',
  150: 'Sys kW Import Demand',
  151: 'Sys kW Export Demand',
  152: 'Sys kVAr Import Demand',
  153: 'Sys kVAr Export Demand',
  154: 'Sys kVA Demand',
  156: 'Sys Current Demand',
  158: 'Sys kW Import Max Demand',
  159: 'Sys kW Export Max Demand',
  160: 'Sys kVAr Import Max Demand',
  161: 'Sys kVAr Export Max Demand',
  162: 'Sys kVA Max Demand',
  164: 'Sys Current Max Demand',
  167: 'kW Import Demand L1',
  168: 'kW Import Demand L2',
  169: 'kW Import Demand L3',
  170: 'kW Export Demand L1',
  171: 'kW Export Demand L2',
  172: 'kW Export Demand L3',
  173: 'kVAr Import Demand L1',
  174: 'kVAr Import Demand L2',
  175: 'kVAr Import Demand L3',
  176: 'kVAr Export Demand L1',
  177: 'kVAr Export Demand L2',
  178: 'kVAr Export Demand L3',
  179: 'kVA Demand L1',
  180: 'kVA Demand L2',
  181: 'kVA Demand L3',
  184: 'Current Demand L1',
  185: 'Current Demand L2',
  186: 'Current Demand L3',
  190: 'kW Import Max Demand L1',
  191: 'kW Import Max Demand L2',
  192: 'kW Import Max Demand L3',
  193: 'kW Export Max Demand L1',
  194: 'kW Export Max Demand L2',
  195: 'kW Export Max Demand L3',
  196: 'kVAr Import Max Demand L1',
  197: 'kVAr Import Max Demand L2',
  198: 'kVAr Import Max Demand L3',
  199: 'kVAr Export Max Demand L1',
  200: 'kVAr Export Max Demand L2',
  201: 'kVAr Export Max Demand L3',
  202: 'kVA Max Demand L1',
  203: 'kVA Max Demand L2',
  204: 'kVA Max Demand L3',
  208: 'Current Max Demand L1',
  209: 'Current Max Demand L2',
  210: 'Current Max Demand L3',
}

export const IO_MAP = {
  1: 'Voltage',
  2: 'Current',
}

// Configuration groups for accordion display
export const MODBUS_CARDS = [
  { address: 6002, count: 40, title: 'System Settings' },
  { address: 6248, count: 18, title: 'AO1 Configuration' },
  { address: 6266, count: 18, title: 'AO2 Configuration' },
  { address: 6284, count: 18, title: 'AO3 Configuration' },
  { address: 6302, count: 18, title: 'AO4 Configuration' },
]

// Reading measurement list for modal
export const READING_LIST: Record<
  number,
  { name: string; category: string; icon: string; color: string; unit: string }
> = {
  0: { name: 'Voltage L1', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  2: { name: 'Voltage L2', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  4: { name: 'Voltage L3', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  200: { name: 'Voltage L12', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  202: { name: 'Voltage L23', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  204: { name: 'Voltage L31', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  70: { name: 'Frequency', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'Hz' },
  42: { name: 'Voltage System', category: 'Voltage', icon: 'ti-bolt', color: 'primary', unit: 'V' },
  6: { name: 'Current L1', category: 'Current', icon: 'ti-activity', color: 'info', unit: 'A' },
  8: { name: 'Current L2', category: 'Current', icon: 'ti-activity', color: 'info', unit: 'A' },
  10: { name: 'Current L3', category: 'Current', icon: 'ti-activity', color: 'info', unit: 'A' },
  46: { name: 'Current System', category: 'Current', icon: 'ti-activity', color: 'info', unit: 'A' },
  12: { name: 'Watt L1', category: 'Power', icon: 'ti-bolt', color: 'warning', unit: 'W' },
  14: { name: 'Watt L2', category: 'Power', icon: 'ti-bolt', color: 'warning', unit: 'W' },
  16: { name: 'Watt L3', category: 'Power', icon: 'ti-bolt', color: 'warning', unit: 'W' },
  52: { name: 'Watt System', category: 'Power', icon: 'ti-bolt', color: 'warning', unit: 'W' },
  18: { name: 'VA L1', category: 'Power', icon: 'ti-bolt', color: 'success', unit: 'VA' },
  20: { name: 'VA L2', category: 'Power', icon: 'ti-bolt', color: 'success', unit: 'VA' },
  22: { name: 'VA L3', category: 'Power', icon: 'ti-bolt', color: 'success', unit: 'VA' },
  56: { name: 'VA System', category: 'Power', icon: 'ti-bolt', color: 'success', unit: 'VA' },
  24: { name: 'VAr L1', category: 'Power', icon: 'ti-bolt', color: 'danger', unit: 'VAr' },
  26: { name: 'VAr L2', category: 'Power', icon: 'ti-bolt', color: 'danger', unit: 'VAr' },
  28: { name: 'VAr L3', category: 'Power', icon: 'ti-bolt', color: 'danger', unit: 'VAr' },
  60: { name: 'VAr System', category: 'Power', icon: 'ti-bolt', color: 'danger', unit: 'VAr' },
  30: { name: 'PF L1', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '' },
  32: { name: 'PF L2', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '' },
  34: { name: 'PF L3', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '' },
  62: { name: 'PF System', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '' },
  36: { name: 'PA L1', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '°' },
  38: { name: 'PA L2', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '°' },
  40: { name: 'PA L3', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '°' },
  66: { name: 'PA System', category: 'PF and Angle', icon: 'ti-angle', color: 'secondary', unit: '°' },
}

// Special addresses that should show dropdowns
export const SPECIAL_ADDRESSES = {
  SYSTEM_TYPE: 6002,
  PARAM_SELECTS: [6250, 6268, 6286, 6304],
  IO_TYPES: [6248, 6266, 6284, 6302],
}
